rm(list = ls())
library(rstan)
options(mc.cores = parallel::detectCores(),Ncpus = parallel::detectCores())
rstan_options(auto_write = TRUE)
setwd("Simulations/Stan_models")
Stan_simulate_ns_matern = stan_model("simulate.stan")
Stan_fit_linear_nngp_ns_matern = stan_model("Non_stationary_fitting_nngp.stan")
Stan_fit_linear_full_ns_matern = stan_model("Non_stationary_fitting.stan")
setwd("../..")
